### ISSUE TITLE
link unavailable when Building the goagent

### ISSUE THREAD

**Issue by nitinkap** [aws-samples/aws-iot-jobs-full-system-update#1]
go get github.com/aws-samples/goagent

**Comment by massi-ang** [comment]
Fixed README. Please check the instructions from the point where to install the goagent. 
Requires go 1.12 or above

**Comment by nitinkap** [comment]
Thanks massi for changes but still there is one issue while  generating the image and the mender artifact
![Screenshot (8)](https://user-images.githubusercontent.com/71751757/94520431-e7d07a80-0249-11eb-858b-3780d66ee31b.png)

**Comment by massi-ang** [comment]
Try running
```
env MENDER_ARTIFACT_NAME="release-1" ./files/mender-env.sh 2019-04-08-raspbian-stretch-lite
```

**Comment by nitinkap** [comment]
> Try running
> 
> ```
> env MENDER_ARTIFACT_NAME="release-1" ./files/mender-env.sh 2019-04-08-raspbian-stretch-lite
> ```

![Screenshot (9)](https://user-images.githubusercontent.com/71751757/94525641-fc187580-0251-11eb-972b-42a9627f0ee9.png)
