### ISSUE TITLE
issue while generating the image and the mender artifact

### ISSUE THREAD

**Issue by nitinkap** [aws-samples/aws-iot-jobs-full-system-update#2]
Thanks massi for changes but still there is one issue while generating the image and the mender artifact.
![Screenshot (8)](https://user-images.githubusercontent.com/71751757/94520960-d5a30c00-024a-11eb-903f-f022b8ed6e16.png)

**Comment by massi-ang** [comment]
Thanks for reporting this. Apparently the `mender-convert` tool has changed.

**Comment by massi-ang** [comment]
You can try cloning again the mender-convert repo using

`git clone -b 1.2.2 https://github.com/mendersoftware/mender-convert.git`

The 1.2 version should be compatible with the current script. I'll provide a fix for using the latest mender-convert.

**Comment by nitinkap** [comment]
Thanks massi now from 

> You can try cloning again the mender-convert repo using
> 
> `git clone -b 1.2.2 https://github.com/mendersoftware/mender-convert.git`
> 
> The 1.2 version should be compatible with the current script. I'll provide a fix for using the latest mender-convert.

Thanks massi ....  I am able to bulid image now and other steps ...
but if you could help with this the agent Failed with exit code
![Screenshot (10)](https://user-images.githubusercontent.com/71751757/94589614-1af32800-02a3-11eb-9570-6ddd9cf857dd.png)
and goagent logs are 
![Screenshot (11)](https://user-images.githubusercontent.com/71751757/94589805-61488700-02a3-11eb-9512-c0908086f4f9.png)

**Comment by massi-ang** [comment]
I cannot reproduce the issue as it works fine on my device. Is the certificate status "ACTIVE" in AWS IoT Core? Does it have a policy allowing the device to connect? Can you ping the aws iot endpoint you have specified in the /etc/goagent/goagent.conf file?

**Comment by nitinkap** [comment]
Yes certificate  is Active in Aws IoT core. Policy is there and I am able to ping the endpoint that i have specified in goagent.conf file.
![Screenshot (12)](https://user-images.githubusercontent.com/71751757/94666049-8fbd7500-032a-11eb-8d6b-e5e59dc32730.png)

**Comment by massi-ang** [comment]
I see that now it is working fine. Have you found out why you were getting the error?

**Comment by nitinkap** [comment]
> I see that now it is working fine. Have you found out why you were getting the error?

No it is not working stuck there and logs are same as mentioned.
![Screenshot (13)](https://user-images.githubusercontent.com/71751757/94686517-8d6a1380-0348-11eb-96c0-2be05e9bd6ad.png)

**Comment by massi-ang** [comment]
I see. As I cannot reproduce the issue, I need your help to get to the root cause of the problem.

Can you try to connect to the same endpoint, using the same certificates using another MQTT client? You can use the pubsub.py sample in https://github.com/aws/aws-iot-device-sdk-python-v2/tree/master/samples. 

Usage : https://github.com/aws/aws-iot-device-sdk-python-v2/tree/master/samples#pubsub


Let me know if you can connect with that.

**Comment by nitinkap** [comment]
> I see. As I cannot reproduce the issue, I need your help to get to the root cause of the problem.
> 
> Can you try to connect to the same endpoint, using the same certificates using another MQTT client? You can use the pubsub.py sample in https://github.com/aws/aws-iot-device-sdk-python-v2/tree/master/samples.
> 
> Usage : https://github.com/aws/aws-iot-device-sdk-python-v2/tree/master/samples#pubsub
> 
> Let me know if you can connect with that.

Yes massi, I am able to connect with same certs and same endpoint with another MQTT client.
![Screenshot (15)](https://user-images.githubusercontent.com/71751757/94727158-f028d280-037b-11eb-8ee4-9e23677a34e0.png)
![Screenshot (16)](https://user-images.githubusercontent.com/71751757/94727174-f323c300-037b-11eb-961e-eaebf7bf00f5.png)
![Screenshot (17)](https://user-images.githubusercontent.com/71751757/94727326-2fefba00-037c-11eb-809f-b24ce01f6975.png)

**Comment by massi-ang** [comment]
I found the issue and fixed it. 
Checkout the repo again using the `-b mender-1.2` switch (see README) and then try generating the image again.
Make a copy `files` folder with your changes before doing a new checkout or use a different folder and then copy those files back

**Comment by nitinkap** [comment]
> I found the issue and fixed it.
> Checkout the repo again using the `-b mender-1.2` switch (see README) and then try generating the image again.
> Make a copy `files` folder with your changes before doing a new checkout or use a different folder and then copy those files back

Hello Massi,
Thanks for your time .Now device is  connected and subscribed  successfully using 
git clone -b 2.2.0 https://github.com/mendersoftware/mender-convert.git.
![Screenshot (18)](https://user-images.githubusercontent.com/71751757/95080250-730fab80-0735-11eb-95f9-2d9891aecb92.png)


While Monitoring the progress of AWS IoT Jobs it stucks in queued.
![Screenshot (19)](https://user-images.githubusercontent.com/71751757/95080768-385a4300-0736-11eb-86a2-1a12adcf9433.png)

![Screenshot (20)](https://user-images.githubusercontent.com/71751757/95080574-ec0f0300-0735-11eb-98e4-4b56f11ed529.png)

**Comment by nitinkap** [comment]
> I found the issue and fixed it.
> Checkout the repo again using the `-b mender-1.2` switch (see README) and then try generating the image again.
> Make a copy `files` folder with your changes before doing a new checkout or use a different folder and then copy those files back

Hi Massi need your help with this jobs stuck in queued state.

Thanks

**Comment by massi-ang** [comment]
The job is waiting for the thing that you targeted to receive it.

Check that clientId and thingName in the `/etc/goagent/goagent.conf` file match the thingName selected for the job.

**Comment by nitinkap** [comment]
Thanks for giving me your valuable time.
